name: dash_kit_core
description: The core component for DashKit that provides basic architecture components
version: 2.1.0
homepage: https://github.com/Dash-Kit/dash-kit-core

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async_redux: ^7.0.2
  built_collection: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.4

flutter:
