name: flutter_platform_core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.6.0
  redux_epics: ^0.14.0
  flutter_hooks: ^0.9.0

  rxdart: ^0.24.0
  equatable: ^0.5.1
  built_collection: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.5.3

flutter:
